repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.20.0
    hooks:
      - id: markdownlint-cli2
        language_version: system
  - repo: local
    hooks:
      - id: backend-code-quality
        name: "backend: code quality"
        entry: task backend:check
        language: system
        pass_filenames: false
        files: ^backend/

      - id: backend-typecheck
        name: "backend: type check"
        entry: task backend:typecheck
        language: system
        pass_filenames: false
        files: ^backend/

      - id: frontend-code-quality
        name: "frontend: code quality"
        entry: task frontend:check
        language: system
        pass_filenames: false
        files: ^frontend/

      - id: frontend-typecheck
        name: "frontend: type check"
        entry: task frontend:check:types
        language: system
        pass_filenames: false
        files: ^frontend/
